version: '2.1'
#volumes:
#  resin-data: {}
#networks:
#  connectors:

services:
  raspberrypi_web_server:
    image: andreasfedermann/raspberrypiwebserver:latest
    #working_dir:
    #mem_limit: 250mb
    #volumes:

    #networks:

    #restart: always
    #depends_on:     
    #command: 
  
# https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.0
# https://hub.docker.com/_/nginx/
  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"