ARG baseAppFolder

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM base AS final
WORKDIR /app
COPY /${baseAppFolder} .
ENTRYPOINT ["dotnet", "RaspberryPiWebserver.dll"]